// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: poseEstimation.proto
#ifndef GRPC_poseEstimation_2eproto__INCLUDED
#define GRPC_poseEstimation_2eproto__INCLUDED

#include "poseEstimation.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace pose_estimation {

class PoseEstimationService final {
 public:
  static constexpr char const* service_full_name() {
    return "pose_estimation.PoseEstimationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::pose_estimation::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pose_estimation::Response>> AsyncPoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pose_estimation::Response>>(AsyncPoseEstimationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pose_estimation::Response>> PrepareAsyncPoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pose_estimation::Response>>(PrepareAsyncPoseEstimationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pose_estimation::Response>* AsyncPoseEstimationRaw(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pose_estimation::Response>* PrepareAsyncPoseEstimationRaw(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::pose_estimation::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pose_estimation::Response>> AsyncPoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pose_estimation::Response>>(AsyncPoseEstimationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pose_estimation::Response>> PrepareAsyncPoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pose_estimation::Response>>(PrepareAsyncPoseEstimationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response, std::function<void(::grpc::Status)>) override;
      void PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pose_estimation::Response>* AsyncPoseEstimationRaw(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pose_estimation::Response>* PrepareAsyncPoseEstimationRaw(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PoseEstimation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PoseEstimation(::grpc::ServerContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PoseEstimation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PoseEstimation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PoseEstimation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PoseEstimation(::grpc::ServerContext* /*context*/, const ::pose_estimation::Request* /*request*/, ::pose_estimation::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPoseEstimation(::grpc::ServerContext* context, ::pose_estimation::Request* request, ::grpc::ServerAsyncResponseWriter< ::pose_estimation::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PoseEstimation<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PoseEstimation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PoseEstimation() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pose_estimation::Request, ::pose_estimation::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response) { return this->PoseEstimation(context, request, response); }));}
    void SetMessageAllocatorFor_PoseEstimation(
        ::grpc::MessageAllocator< ::pose_estimation::Request, ::pose_estimation::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pose_estimation::Request, ::pose_estimation::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PoseEstimation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PoseEstimation(::grpc::ServerContext* /*context*/, const ::pose_estimation::Request* /*request*/, ::pose_estimation::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PoseEstimation(
      ::grpc::CallbackServerContext* /*context*/, const ::pose_estimation::Request* /*request*/, ::pose_estimation::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PoseEstimation<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PoseEstimation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PoseEstimation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PoseEstimation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PoseEstimation(::grpc::ServerContext* /*context*/, const ::pose_estimation::Request* /*request*/, ::pose_estimation::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PoseEstimation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PoseEstimation() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PoseEstimation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PoseEstimation(::grpc::ServerContext* /*context*/, const ::pose_estimation::Request* /*request*/, ::pose_estimation::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPoseEstimation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PoseEstimation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PoseEstimation() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PoseEstimation(context, request, response); }));
    }
    ~WithRawCallbackMethod_PoseEstimation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PoseEstimation(::grpc::ServerContext* /*context*/, const ::pose_estimation::Request* /*request*/, ::pose_estimation::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PoseEstimation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PoseEstimation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PoseEstimation() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pose_estimation::Request, ::pose_estimation::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pose_estimation::Request, ::pose_estimation::Response>* streamer) {
                       return this->StreamedPoseEstimation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PoseEstimation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PoseEstimation(::grpc::ServerContext* /*context*/, const ::pose_estimation::Request* /*request*/, ::pose_estimation::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPoseEstimation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pose_estimation::Request,::pose_estimation::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PoseEstimation<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PoseEstimation<Service > StreamedService;
};

}  // namespace pose_estimation


#endif  // GRPC_poseEstimation_2eproto__INCLUDED
