// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: poseEstimation.proto

#include "poseEstimation.pb.h"
#include "poseEstimation.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace pose_estimation {

static const char* PoseEstimationService_method_names[] = {
  "/pose_estimation.PoseEstimationService/PoseEstimation",
};

std::unique_ptr< PoseEstimationService::Stub> PoseEstimationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PoseEstimationService::Stub> stub(new PoseEstimationService::Stub(channel, options));
  return stub;
}

PoseEstimationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PoseEstimation_(PoseEstimationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PoseEstimationService::Stub::PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::pose_estimation::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pose_estimation::Request, ::pose_estimation::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PoseEstimation_, context, request, response);
}

void PoseEstimationService::Stub::async::PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pose_estimation::Request, ::pose_estimation::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PoseEstimation_, context, request, response, std::move(f));
}

void PoseEstimationService::Stub::async::PoseEstimation(::grpc::ClientContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PoseEstimation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pose_estimation::Response>* PoseEstimationService::Stub::PrepareAsyncPoseEstimationRaw(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pose_estimation::Response, ::pose_estimation::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PoseEstimation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pose_estimation::Response>* PoseEstimationService::Stub::AsyncPoseEstimationRaw(::grpc::ClientContext* context, const ::pose_estimation::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPoseEstimationRaw(context, request, cq);
  result->StartCall();
  return result;
}

PoseEstimationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PoseEstimationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PoseEstimationService::Service, ::pose_estimation::Request, ::pose_estimation::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PoseEstimationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pose_estimation::Request* req,
             ::pose_estimation::Response* resp) {
               return service->PoseEstimation(ctx, req, resp);
             }, this)));
}

PoseEstimationService::Service::~Service() {
}

::grpc::Status PoseEstimationService::Service::PoseEstimation(::grpc::ServerContext* context, const ::pose_estimation::Request* request, ::pose_estimation::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pose_estimation

